/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.FriendsController;
import javax.swing.table.DefaultTableModel;

public class FrmFriendsTop extends javax.swing.JFrame {
    private FriendsController friendsController;

    public FrmFriendsTop(FriendsController controller) {
        initComponents();
        this.friendsController = controller;
        this.btnBack.addActionListener(friendsController); 
        this.btnDelete.addActionListener(friendsController);
        this.btnTop.addActionListener(friendsController);  
        this.btnRecent.addActionListener(friendsController);
        loadFriends();
        setLocationRelativeTo(null);
    }
    

    public void loadFriends() {
    DefaultTableModel model = friendsController.getFriendsTableModel(false);// con orden de Mas recientes
    tblTopFriends.setModel(model);
}
    
    public void loadFriendsByLevel() {
    DefaultTableModel model = friendsController.getFriendsTableModel(true); // Con orden de nivel
    tblTopFriends.setModel(model);
}
    
    public int getSelectedRow() {
        return tblTopFriends.getSelectedRow();
    }

    public String getFriendUsernameAtRow(int row) {
        return tblTopFriends.getValueAt(row, 0).toString(); // columna 0: username
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTop = new javax.swing.JButton();
        btnRecent = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTopFriends = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonTopFriends.png"))); // NOI18N
        btnTop.setActionCommand("Top");
        btnTop.setBorderPainted(false);
        btnTop.setContentAreaFilled(false);
        getContentPane().add(btnTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        btnRecent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonRecentFriends.png"))); // NOI18N
        btnRecent.setActionCommand("Recent");
        btnRecent.setBorderPainted(false);
        btnRecent.setContentAreaFilled(false);
        btnRecent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecentActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecent, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonDeleteFriend.png"))); // NOI18N
        btnDelete.setActionCommand("Delete");
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        tblTopFriends.setBackground(new java.awt.Color(204, 204, 255));
        tblTopFriends.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTopFriends.setGridColor(new java.awt.Color(153, 153, 255));
        jScrollPane1.setViewportView(tblTopFriends);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 510, 310));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnBack.setActionCommand("Back1");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRecentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecentActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRecent;
    private javax.swing.JButton btnTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTopFriends;
    // End of variables declaration//GEN-END:variables
}
