/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionListener;


public class FrmHome extends javax.swing.JFrame {

    /**
     * Creates new form FrmHome
     */
    public FrmHome() {
        initComponents();
    }

     public void listenButtons(ActionListener controller){
        this.btnLogOut.addActionListener(controller);
        this.btnFriends.addActionListener(controller);
        this.btnWorkOut.addActionListener(controller);
        this.btnProfile.addActionListener(controller);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogOut = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnFriends = new javax.swing.JButton();
        btnWorkOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogOut.setText("Exit");
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 662, 134, 53));

        btnProfile.setText("Profile");
        getContentPane().add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 662, 134, 53));

        btnFriends.setText("Friends");
        getContentPane().add(btnFriends, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 26, 134, 53));

        btnWorkOut.setText("Workout");
        getContentPane().add(btnWorkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 662, 134, 53));

        jLabel1.setText("BiggestBooty");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 335, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFriends;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnWorkOut;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
