/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.User;
import java.awt.event.ActionListener;


public class FrmUser extends javax.swing.JFrame {

    /**
     * Creates new form FrmUser
     */
    public FrmUser() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    
    public void setListenFrmUser(ActionListener controller)
    {
     this.btnEdit.addActionListener(controller);
     this.btnBack.addActionListener(controller);   
    }

    public void setUserData(User user)
    {
        lblUsername.setText(user.getUsername());
        lblLevel.setText(String.valueOf(user.getLevel()));
        txtAge.setText(String.valueOf(user.getAge()));
        txtWeight.setText(String.valueOf(user.getWeight()));
        txtGenre.setText(user.getSex());
    }
    
    public String getAge() {
        return txtAge.getText();
    }

    public String getWeight() {
        return txtWeight.getText();
    }

    public String getGenre() {
        return txtGenre.getText();
    }
    
    public void updateLevelDisplay(int newLevel) {
    lblLevel.setText("Level: " + newLevel);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLevel = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLevel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblLevel.setForeground(new java.awt.Color(0, 0, 0));
        lblLevel.setText("Level");
        getContentPane().add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 130, 20));

        lblUsername.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername.setText("Username");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 130, 20));
        getContentPane().add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 130, -1));
        getContentPane().add(txtGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 130, -1));
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 130, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonBackUser.png"))); // NOI18N
        btnBack.setActionCommand("BackUser");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 526, 125, 59));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonEditUser.png"))); // NOI18N
        btnEdit.setActionCommand("EditUser");
        btnEdit.setBorderPainted(false);
        btnEdit.setContentAreaFilled(false);
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 210, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FrmUser.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
